from __future__ import annotations

from pathlib import Path
from typing import Optional

from fastapi import FastAPI, HTTPException, Query, Request
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates

from . import db
from .settings import DB_PATH, EXTRACTED_DIR, LOGO_PATH

app = FastAPI(title="Military Dictionary", version="0.1.0")

BASE_DIR = Path(__file__).resolve().parent

templates = Jinja2Templates(directory=str(BASE_DIR / "templates"))

# static assets for the new UI
app.mount("/static", StaticFiles(directory=str(BASE_DIR / "static")), name="static")

# expose extracted images (generated by tools/extract_documents.py)
if EXTRACTED_DIR.exists():
    app.mount("/extracted", StaticFiles(directory=str(EXTRACTED_DIR)), name="extracted")


@app.get("/health")
def health() -> dict:
    return {"ok": True, "db": str(DB_PATH)}


@app.get("/", response_class=HTMLResponse)
def home(request: Request):
    with db.get_conn() as conn:
        sections = db.list_sections(conn)

    return templates.TemplateResponse(
        "home.html",
        {
            "request": request,
            "sections": sections,
        },
    )


@app.get("/sections/{section_number}", response_class=HTMLResponse)
def section_page(
    request: Request,
    section_number: int,
    q: str = Query("", description="Search query"),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=10, le=200),
):
    offset = (page - 1) * page_size
    with db.get_conn() as conn:
        section = db.get_section(conn, section_number)
        if not section:
            raise HTTPException(status_code=404, detail="Section not found")

        items, total = db.search_terms(conn, q=q, section_number=section_number, limit=page_size, offset=offset)

    total_pages = max(1, (total + page_size - 1) // page_size)
    return templates.TemplateResponse(
        "section.html",
        {
            "request": request,
            "section": section,
            "items": items,
            "q": q,
            "page": page,
            "page_size": page_size,
            "total": total,
            "total_pages": total_pages,
        },
    )


@app.get("/search", response_class=HTMLResponse)
def search_page(
    request: Request,
    q: str = Query("", description="Search query"),
    section: Optional[int] = Query(None, description="Optional section_number"),
    page: int = Query(1, ge=1),
    page_size: int = Query(50, ge=10, le=200),
):
    offset = (page - 1) * page_size
    with db.get_conn() as conn:
        items, total = db.search_terms(conn, q=q, section_number=section, limit=page_size, offset=offset)
        sections = db.list_sections(conn)

    total_pages = max(1, (total + page_size - 1) // page_size)
    return templates.TemplateResponse(
        "search.html",
        {
            "request": request,
            "q": q,
            "section": section,
            "sections": sections,
            "items": items,
            "page": page,
            "page_size": page_size,
            "total": total,
            "total_pages": total_pages,
        },
    )


@app.get("/docs/{section_number}", response_class=HTMLResponse)
def documents_page(request: Request, section_number: int, doc: Optional[int] = None):
    with db.get_conn() as conn:
        section = db.get_section(conn, section_number)
        if not section:
            raise HTTPException(status_code=404, detail="Section not found")

        docs = db.list_documents(conn, section_number)
        active_doc = None
        images = []
        if doc is not None:
            active_doc = db.get_document(conn, doc)
            if not active_doc:
                raise HTTPException(status_code=404, detail="Document not found")
            images = db.list_document_images(conn, doc)
        elif docs:
            active_doc = db.get_document(conn, int(docs[0]["id"]))
            images = db.list_document_images(conn, int(docs[0]["id"]))

    return templates.TemplateResponse(
        "documents.html",
        {
            "request": request,
            "section": section,
            "documents": docs,
            "active_doc": active_doc,
            "images": images,
        },
    )


@app.get("/files/doc/{document_id}")
def serve_document_file(document_id: int):
    with db.get_conn() as conn:
        doc = db.get_document(conn, document_id)
    if not doc:
        raise HTTPException(status_code=404, detail="Document not found")

    resolved = doc.get("resolved_path")
    if not resolved:
        raise HTTPException(status_code=404, detail="File missing")
    path = Path(resolved)

    filename = path.name
    media_type = "application/octet-stream"
    if path.suffix.lower() == ".pdf":
        media_type = "application/pdf"

    return FileResponse(str(path), media_type=media_type, filename=filename)


@app.get("/assets/logo")
def serve_logo():
    if not LOGO_PATH.exists():
        raise HTTPException(status_code=404, detail="Logo missing")
    return FileResponse(str(LOGO_PATH), media_type="image/png")


@app.get("/favicon.ico")
def favicon():
    if LOGO_PATH.exists():
        return FileResponse(str(LOGO_PATH), media_type="image/png")
    raise HTTPException(status_code=404, detail="favicon missing")


# ---- JSON API (optional, usable for a SPA later) ----

@app.get("/api/sections")
def api_sections():
    with db.get_conn() as conn:
        return db.list_sections(conn)


@app.get("/api/sections/{section_number}/terms")
def api_section_terms(
    section_number: int,
    q: str = "",
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    with db.get_conn() as conn:
        section = db.get_section(conn, section_number)
        if not section:
            raise HTTPException(status_code=404, detail="Section not found")
        items, total = db.search_terms(conn, q=q, section_number=section_number, limit=limit, offset=offset)
        return {"items": items, "total": total}


@app.get("/api/terms/search")
def api_search_terms(
    q: str = "",
    section: Optional[int] = None,
    limit: int = Query(50, ge=1, le=200),
    offset: int = Query(0, ge=0),
):
    with db.get_conn() as conn:
        items, total = db.search_terms(conn, q=q, section_number=section, limit=limit, offset=offset)
        return {"items": items, "total": total}


@app.get("/api/sections/{section_number}/documents")
def api_documents(section_number: int):
    with db.get_conn() as conn:
        return db.list_documents(conn, section_number)


@app.get("/api/documents/{document_id}/images")
def api_document_images(document_id: int):
    with db.get_conn() as conn:
        doc = db.get_document(conn, document_id)
        if not doc:
            raise HTTPException(status_code=404, detail="Document not found")
        return db.list_document_images(conn, document_id)
